### ISSUE TITLE
Emojify source code

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#10]
Some languages such as Javascript, Swift, PHP and Java allow Unicode emoji outside of comments and strings. You might see code like this:

    for(💜 in 💕) { 🎵(💜); }

Those should be emojified. We could fix this by making `emojify-prog-contexts` restrictions apply only to ASCII- and github-style emojis.

**Comment by iqbalansari** [comment]
I agree with @ryanprior's suggestion, @cpitclaudel what do you think?

**Comment by cpitclaudel** [comment]
Works for me! Sorry for opening a duplicate. I like @ryanprior's suggestion.
It could also work to add a setting to `emojify-prog-contexts` to emojify everywhere.

**Comment by ryanprior** [comment]
I can't picture wanting emojification of ascii or fenced styles in source code for anything except comments and maaaaybe strings. Is that reasonable? Do you see somebody wanting to legitimately name a variable `:rainbow:` or define `#-)` as an operator and expect those to automatically be emojified?

I do expect to see people increasingly use emoji in source code, but I picture Unicode and extensions like prettify-symbols as the preferred ways of accomplishing that.

**Comment by cpitclaudel** [comment]
> I can't picture wanting emojification of ascii or fenced styles in source code for anything except comments and maaaaybe strings. Is that reasonable? Do you see somebody wanting to legitimately name a variable :rainbow: or define #-) as an operator and expect those to automatically be emojified?

No, not really.

> I do expect to see people increasingly use emoji in source code, but I picture Unicode and extensions like prettify-symbols as the preferred ways of accomplishing that.

I sometimes use prettify-symbols-mode to display the `self` keyword in python as 👤. Having it show an actual emoji, instead of the outline that Symbola provides, would be nice.

For me this package is superior to prettify-symbols for certain use cases, as it allows me to prettify a string into an image, instead of prettifying it into a Unicode character. If Emacs had support for displaying color Emojis embedded in a font all would be good for me, but it doesn't on Linux, so this package definitely fills a gap.

**Comment by iqbalansari** [comment]
@ryanprior, @cpitclaudel  I have pushed some changes to master which make this possible. Please do try it out when MELPA builds and report back problems if any.

Thanks

**Comment by mohkale** [comment]
Just curious if there's a way to enable github styles emojis in code outside of strings? For example, I'd like to be able to use my scratch buffer to test out different emojis, but it only renders github style emojis when their in a string. Seeing as `lisp-interaction-mod`e is kind of in between a program-mode and a text-mode, I think there should be an in-between solution.
