### ISSUE TITLE
Gets stuck on Contacting host: raw.githubusercontent.com:443

### ISSUE THREAD

**Issue by Celibistrial** [iqbalansari/emacs-emojify#106]
I am using doom-emacs
After installing emojify  it asks if i want to download the emoji images and then it gets stick 
```
[emojify] Emoji images not available should I download them now? (y or n) y
[emojify] Emoji images not available should I download them now? (y or n) y
Contacting host: raw.githubusercontent.com:443
```

**Comment by Celibistrial** [comment]
for anyone else having this issue changing your DNS might fix it
some ISPs block raw raw.githubusercontent.com

**Comment by binarydigitz01** [comment]
I did change DNS to 1.1.1.1, but it's still not working. Most users in India should be facing issues, as it is blocked by ISP due to goverment orders... Need guidance

**Comment by Celibistrial** [comment]
You have to change DNS systemwide (ipv4&ipv6)
This command should change them to Cloudflare's DNS(Replace your network name)
 `nmcli con modify myNetworkName +ipv4.dns 1.1.1.1 && nmcli con modify myNetworkName +ipv6.dns 2606:4700:4700::1111`
