### ISSUE TITLE
emojify-delete-emoji misbehaving

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#11]
steps to reproduce
--
1. open emacs
1. write in a text buffer
![plain](https://cloud.githubusercontent.com/assets/4389854/11328078/8108312a-9148-11e5-846b-965405cae3f5.png)
1. activate `emojify-mode`
    ![emoji](https://cloud.githubusercontent.com/assets/4389854/11328085/8b50a31a-9148-11e5-916d-c2b4202b3ac6.png)
1. put the cursor between the :elephant: and the :whale: (whale is highlighted)
1. press delete key

### expected outcome
whale is deleted
### actual outcome
a `:` character takes the whale's place.
![deleted](https://cloud.githubusercontent.com/assets/4389854/11328111/cd9bc6e6-9148-11e5-8293-e4b20544f53b.png)
#### observations
Turning off `emojify-mode` after step 5 reveals that there is no extra `:` character inserted into the buffer. Re-engaging `emojify-mode` does not reintroduce the stray marks.

using
--
* emojify 20151122.813
* Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2015-11-21

**Comment by iqbalansari** [comment]
This seems to be happening only on latest unreleased Emacs, I tried this on last stable release (24.5) and it seems to be working fine. Let me investigate this further tonight, perhaps we have hit a bug in Emacs.

**Comment by iqbalansari** [comment]
This has been fixed on master, could you please try it when MELPA builds and report back. Thanks

**Comment by ryanprior** [comment]
I confirm this is fixed in emojify 20151126.2104 with Emacs 25.0.50.4 of 2015-11-27.

**Comment by iqbalansari** [comment]
Great, thanks for confirming!
