### ISSUE TITLE
Type of emojis to be displayed should be customizable on a per-mode basis

### ISSUE THREAD

**Issue by iqbalansari** [iqbalansari/emacs-emojify#13]
See https://github.com/iqbalansari/emacs-emojify/pull/12#issuecomment-164493246

**Comment by leafac** [comment]
Now that I understand better how emojify works, I don't think the feature proposed by this PR is really necessary. If we have good detection of `prog-mode` and its variations, we shouldn't need to add exceptions for this or that emoji on this or that mode. Also, it would make the configuration harder to understand, use and maintain.

**Comment by ryanprior** [comment]
I agree that it's not necessary until there's a compelling use case. For example, #10 could present one, but we're not there yet.

**Comment by iqbalansari** [comment]
Closing this issue for now. In addition to points mentioned by @leafac, I think the variable `emojify-inhibit-functions` provides the most general mechanism to inhibit the display of emojis,  so this can be achieved through user customizations (if desired).
