### ISSUE TITLE
Interaction with prettify-symbols-mode

### ISSUE THREAD

**Issue by cpitclaudel** [iqbalansari/emacs-emojify#16]
Hi @iqbalansari,

This package looks beautiful :) Do you think there would be a way to make it work with prettify-symbols-mode? I often use prettify-symbols-mode to shorten the display of common programming symbols, but of course typing the emoji directly wouldn't work (it wouldn't be proper syntax). Could emojify still work in that situation?

Here's an example of a prettify-symbols table that uses emoji:

```elisp
(defvar python-prettify-symbols-alist
  '(("lambda" . ?λ)
    ("self" . ?自)
    ("yield" . ?⇢)
    ("return" . ?↪)
    ("try" . ?😱) ;; ⚠
    ("except" . ?⛐)
    ("raise" . ?💥)
    ("assert" . ?✓)
    ("<=" . ?≤)
    (">=" . ?≥)
    ("!=" . ?≠)
    ("or" . ?∨)
    ("and" . ?∧)
    ("None" . ?⊥)
    ("set()" . ?∅)
    ("not in" . ?∉)
    ("in" . ?∈)
    ("is not" . ?≢)
    ("is" . ?≡)))
```

**Comment by iqbalansari** [comment]
Hi,

I am glad you like the package.

Unfortunately AFAIK it might not be possible to integrate this with `prettify-symbol-mode` atleast not using the current mechanism, since `prettify-symbols-mode` uses the `composition` text property to render the desired keywords with `symbols`. As such `emojify` would not be able to search for the text to be displayed as emoji. 

However this might be possible via a different mechanism (I am just thinking out aloud), emojify can search for the text which have `composition` text property set and if the value is an `emoji`, it can render the underlying text as image. Your thoughts?

**Comment by cpitclaudel** [comment]
This definitely sounds like a good idea!
Another option could be to parse the prettify-symbols table and remove the entries that emojify can handle, adding the instead to emojify's own tables.

**Comment by iqbalansari** [comment]
Hi @cpitclaudel,

I have implemented support for `prettify-symbols-mode` on a [branch](https://github.com/iqbalansari/emacs-emojify/tree/pretty-symbols-integration), would it be possible for you to give it a [try](https://github.com/iqbalansari/emacs-emojify/tree/pretty-symbols-integration#integration-with-prettify-symbol-mode) before I push it to MELPA?

Thanks

**Comment by cpitclaudel** [comment]
Sure; do I just check that branch out?

**Comment by iqbalansari** [comment]
Yes that should do it

**Comment by cpitclaudel** [comment]
This isn't working for me; maybe I'm doing something wrong.

 I have:

```
(setq prettify-symbols-alist '(("lambda" . 955)
 ("self" . 33258)
 ("yield" . 8674)
 ("return" . 8618)
 ("try" . 128561)
 ("except" . 9936)
 ("raise" . 128165)
 ("assert" . 10003)))
```

and I ran `(emojify-set-emoji-style '(prettify-symbols ascii unicode github))`

Typing an explicit `😱` in the source does yield an emoji, but typing `try` prettifies it to `😱`, which does not get emojified.

**Comment by iqbalansari** [comment]
Sorry my bad, there is a typo in the README, the relevant style here is  `prettify-symbol` not `prettify-symbols`

**Comment by iqbalansari** [comment]
Hi, just wanted to let you know that I have merged this to master, it seemed to be working well with my limited testing. It should be available in the next MELPA build. 

It is disabled by default, to enable it just do

```emacs-lisp
(emojify-set-emoji-style '(prettify-symbol ascii unicode github))
```
 And re-enable `prettify-symbol-mode` if it is already enabled.

**Comment by iqbalansari** [comment]
Hi @cpitclaudel, you got a chance to try this again?

**Comment by cpitclaudel** [comment]
I did! Seems to work great :) I didn't have to re-enable prettify-symbols-mode; it worked out of the box.

Thanks!
