### ISSUE TITLE
Emojify company pseudo-buffers

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#17]
Using `company-emoji` for completions in an emojified buffer should show emojis as they will appear, but right now the Unicode glyphs are displayed instead.

A general enough solution to https://github.com/iqbalansari/emacs-emojify/issues/16#issuecomment-165488559 might be reused for this use purpose.

**Comment by iqbalansari** [comment]
Hmm, I think this might be difficult to achieve, I am not sure if the display property can be applied to text in a overlay.

**Comment by iqbalansari** [comment]
I researched this a bit currently I think this is impossible to do. Text is displayed in overlay using the `display` property. Displaying images also consists of adding the `display` property to some text. As such  to display an image in the overlay I will have to add a `display` property to the text used as `display` property of the overlay. Unfortunately recursive `display` properties are not [supported](https://www.gnu.org/software/emacs/manual/html_node/elisp/Other-Display-Specs.html#Other-Display-Specs).

I am closing this for now, however feel free to reopen if you have an alternate approach in mind.

**Comment by ryanprior** [comment]
Thank you for researching this @iqbalansari.

**Comment by iqbalansari** [comment]
Hi @ryanprior,

Just wanted to inform you `emojify` can now display emoji inside company-mode tooltips. I pushed the change on master it might take some time before it becomes available on MELPA. 

The functionality is disabled by default just set `emojify-company-tooltips-p` to `t` to enable it (and you will also need `emojify-mode` to be on).

Thanks
