### ISSUE TITLE
custom emoji set location

### ISSUE THREAD

**Issue by blaenk** [iqbalansari/emacs-emojify#19]
Love this package by the way.

I noticed that recently I got prompted to download the emoji set and they were placed in `~/.emacs.d/emojis`, but I don't want this there. I actually put all package-related data in `~/.emacs.d/cache` for example. It'd be nice if we could set a path in which the `emojis` folder should be placed, like all other packages do.

Thanks!

**Comment by blaenk** [comment]
My apologies. I should've checked, I found `emojify-emojis-dir` :)

LOVE this package!

**Comment by iqbalansari** [comment]
No problem, that part of the package is underdocumented :). Glad you liked the package!

**Comment by vincentbernat** [comment]
Modifying `emojify-emojis-dir` without modifying `emojify-image-dir` will lead to odd results (endless loop of downloading emojis). Is it worth opening an issue?

**Comment by iqbalansari** [comment]
Hi, 

Thanks for the heads up. I think its worth opening an issue, I will push a fix soon anyways

Thanks

**Comment by vincentbernat** [comment]
Done in #22.
