### ISSUE TITLE
Reference to free variable

### ISSUE THREAD

**Issue by manuel-uberti** [iqbalansari/emacs-emojify#2]
Hi,

I just installed this package from MELPA and added the hook as specified in your documentation. Upon restarting Emacs I get this warning:
```
Warning (bytecomp): reference to free variable ‘emojify-mode’
```
The package is working, though, so it is probably a minor issue.

Thanks for the great work.

**Comment by iqbalansari** [comment]
Thanks for reporting the bug. The warning is because of this [line](https://github.com/iqbalansari/emacs-emojify/blob/cf4f7a4a141691cb269b78d8873513d28b039580/emojify.el#L233). I plan to fix it soon, you can safely ignore it for now. I am leaving this issue open as a reminder.

**Comment by manuel-uberti** [comment]
I just grabbed your latest commit from MELPA, and I still have that warning at startup.

**Comment by iqbalansari** [comment]
That is strange, I cannot reproduce that warning. Can you try manually byte compiling the file (using the command `byte-compile-file`) and report the exact warning?

**Comment by manuel-uberti** [comment]
What file are you referring to? My init.el?

**Comment by iqbalansari** [comment]
Oh sorry for being unclear, I meant the `emojify.el` file in your elpa directory.

**Comment by manuel-uberti** [comment]
Ok, done and restarted Emacs. This is the message from the `*Warnings*` buffer:
```
Warning (bytecomp): reference to free variable ‘emojify-mode’
```

**Comment by iqbalansari** [comment]
Do have an old copy of the library by any chance (try doing `find-library`)? Also did the `byte-compile-file` report any warnings?

**Comment by manuel-uberti** [comment]
- I only have the lastest file from MELPA (only `emojify-20151115.1942/` in my elpa directory)
- `byte-compile-file` reported this:
```
Leaving directory ‘~/.emacs.d/elpa/emojify-20151115.1942/’
Compiling file /home/manuel/.emacs.d/elpa/emojify-20151115.1942/emojify.el at Mon Nov 16 17:22:52 2015
Entering directory ‘/home/manuel/.emacs.d/elpa/emojify-20151115.1942/’
Compiling no file at Mon Nov 16 17:22:54 2015
```

**Comment by iqbalansari** [comment]
I think I got the issue, it seems upstream Emacs has got smarter about byte compilation (the error does not happen on Emacs v24.5), I have pushed a fix on master. Please do report back if it works (or does not work). Thanks for your patience

**Comment by manuel-uberti** [comment]
Thank you, I forgot to mention I'm on Emacs trunk (built yesterday). I'll report back as soon as it is on MELPA.

**Comment by iqbalansari** [comment]
No problem, I too should have remembered to ask for the Emacs version :smile:

**Comment by manuel-uberti** [comment]
Great, you nailed it! :+1: 
Thank you
