### ISSUE TITLE
emojify-program-contexts overwritten by emojify-prog-contexts?

### ISSUE THREAD

**Issue by blaenk** [iqbalansari/emacs-emojify#21]
When I `(setq emojify-program-contexts '(comments))` before emojify loads, it still is given the default value. I think the way it's set up, the obsolete variable prog-contexts' `:set` behavior ends up overwriting the new variable when it's first set.

I resolved it by putting the `setq` after the package loads, but it did take me a long while to realize that the variable was incorrect the whole time so perhaps you can fix it to save others the trouble. Maybe move the `:set` behavior to the new variable? That way since I `setq` the new variable, the old variable's wont have a `:set` behavior which overwrites it.

``` elisp
(defcustom emojify-prog-contexts
  'both
  "Contexts where emojis can be displayed in programming modes.

Possible values are
`comments' - Display emojis only in comments
`string'   - Display emojis only in strings
`both'     - Display emojis in comments and strings
`none'     - Do not display emojis in programming modes"
  :type '(radio :tag "Contexts where emojis should be displayed in programming modes"
                (const :tag "Only in comments" comments)
                (const :tag "Only in string" string)
                (const :tag "Both in comments and string" both)
                (const :tag "Do not display emojis in programming modes" none))
  :set (lambda (_ value)
         (setq emojify-program-contexts (pcase value
                                          (`comments '(comments))
                                          (`string '(string))
                                          (`both '(comments string code))
                                          (`none '()))))
  :group 'emojify)
```

So if I understand correctly, I setq the new variable, but when the old variable initializes it triggers its `:set` behavior (or does it not?), which ends up `setq`'ing the new variable with the default settings ('both).

**Comment by iqbalansari** [comment]
Hi,

Thanks for the bug report and sorry for the inconvenience. `emojify-prog-contexts` has been deprecated for a while now, I am thinking I will remove it completely.

Thanks

**Comment by blaenk** [comment]
No problem. Yeah I know that it's deprecated, that's why I was using `emojify-program-contexts`. This issue is about the fact that `emojify-prog-contexts` ends up overwriting `emojify-program-contexts`'s value. Indeed removing it altogether would resolve this :)

**Comment by iqbalansari** [comment]
Done, thanks for reporting the issue :+1:
