### ISSUE TITLE
Modifying `emojify-emojis-dir` during runtime leads to infinite loops

### ISSUE THREAD

**Issue by vincentbernat** [iqbalansari/emacs-emojify#22]
Hey!

When modifying `emojify-emojis-dir` during runtime (after package is loaded), the emojis are downloaded in one place and searched in another place (`emojify-image-dir`). The other place should be relative to the "running" value of `emojify-emojis-dir`, otherwise the downloaded emojis are not found (and download is proposed again).

**Comment by iqbalansari** [comment]
Hi,

Sorry for the inconvenience, I have pushed a fix to master, please test it once MELPA updates.

Thanks

**Comment by vincentbernat** [comment]
Thanks, this works fine for me!
