### ISSUE TITLE
Emoji not displayed in gnus article

### ISSUE THREAD

**Issue by yhvh** [iqbalansari/emacs-emojify#24]
With global-emojify-mode enabled, I do not see emoji displayed in gnus articles.
If I disable and then enable with article open I see emoji displayed

**Comment by iqbalansari** [comment]
Hi,

Thanks for the bug report, will look into it soon

**Comment by iqbalansari** [comment]
Also it would be helpful if you mention the Gnus group where I could find articles with emojis so that I can reproduce the behavior

Thanks

**Comment by yhvh** [comment]
Works now, no change in environment. Possible package update?

**Comment by iqbalansari** [comment]
Hmm.. actually I have not updated the package, please feel free to re-open if this happens again.
