### ISSUE TITLE
:+1: does not show up as a valid emoji

### ISSUE THREAD

**Issue by jgkamat** [iqbalansari/emacs-emojify#26]
`:+1:` does not turn into a `:thumbsup:` emoji, despite `:thumbsup:` working just fine.

Since people use `:+1:` all over the place, it would be nice to have them automatically coverted to `:thumbsup:` as well as the opposite (`:-1:` to `:thumbsdown:`)

On github this works fine =)
+1 -> :+1: 
thumbsup -> :thumbsup:

**Comment by iqbalansari** [comment]
Hi @jgkamat ,

Thanks for the bug report and sorry for the delayed reply. I have pushed fix on the master branch. Could you please try out the latest version once MELPA updates and report back?

Thanks

**Comment by jgkamat** [comment]
Perfect, this works!

Thanks for solving this so quickly! :smile:
