### ISSUE TITLE
Cannot download emojis images

### ISSUE THREAD

**Issue by anquegi** [iqbalansari/emacs-emojify#31]
I'm using Cask to manage my emacs packages, and after installing emojify I always get this:

```
[emojify] Emoji images not available should I download them now? (y or n) y
Contacting host: github.com:443
Error in post-command-hook (global-emojify-mode-check-buffers): (file-error "Opening output file" "Permission denied" "/tmp11887_vo")
```

**Comment by iqbalansari** [comment]
Hi @anquegi,

Thanks for the bug report. 

This looks wierd. Emojify downloads an archive containing the images to the a temporary file, the temporary file is created by basically doing `(make-temp-name temporary-file-directory)` which returns a unique name (for our purposes at-least) in the temporary directory. The error you posted seems to suggest that the name being constructed is incorrect. What operating system are you using? Could you post the output of running `(make-temp-name temporary-file-directory)` in the `ielm`?

As a temporary workaround you can manually download the images. Basically download the tar file from [`github`](https://github.com/iqbalansari/emacs-emojify/blob/images/emojione-v2.2.6.tar?raw=true) and extract it in the directory `~/.emacs.d/emojis/` and restart your Emacs instance. Something like the below should do the trick

```bash
cd /tmp && wget --trust-server-names https://github.com/iqbalansari/emacs-emojify/blob/images/emojione-v2.2.6.tar?raw=true && mkdir ~/.emacs.d/emojis && tar xvf emojione-v2.2.6.tar -C ~/.emacs.d/emojis/
```

Thanks

**Comment by anquegi** [comment]
Thanks for the temporary work around, it works perfectly.

[](url)
<img width="1280" alt="captura de pantalla 2017-10-18 a las 8 31 38" src="https://user-images.githubusercontent.com/2518346/31716426-00c77ec8-b408-11e7-9ef7-fd5030fc600b.png">

I'm using this:

This is GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-09-12

yesterday I updated(also noticed) to install emacs with brew cask in OSX. 

```
ELISP> (make-temp-name temporary-file-directory)
"/tmp507JJr"
```

**Comment by iqbalansari** [comment]
Hmm... what is the value of the variable `temporary-file-directory`?

**Comment by anquegi** [comment]
ELISP> temporary-file-directory
"/tmp"

**Comment by iqbalansari** [comment]
There was a really stupid bug in my code I have pushed a fix on master, if possible could you test it once MELPA updates?

After the package updates kill the current Emacs instance, delete the `~/.emacs.d/emojis` directory and restart Emacs, `emojify` should automatically download the images.

Thanks

**Comment by anquegi** [comment]
Thanks it worked well after updating and removing:

```
╭─ ~/.emacs.d  2.4.0@learn  Version 1.11-r16635 (DarwinX8664)  master 
╰─ rm -rf emojis                                                                                                                                                                                                        ✓  9015  15:57:28
╭─ ~/.emacs.d  2.4.0@learn  Version 1.11-r16635 (DarwinX8664)  master ● 
╰─ cask --verbose update                                                                                                                                                                                                ✓  9016  15:57:34
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Loading async...
Updated packages:
```
...
emojify 20170709.207 -> 20171018.744
...
```

<img width="1280" alt="captura de pantalla 2017-10-19 a las 16 01 40" src="https://user-images.githubusercontent.com/2518346/31774806-135693e6-b4e7-11e7-9ba6-c84c4c68d200.png">
