### ISSUE TITLE
Not an Issue, just a thank you note.

### ISSUE THREAD

**Issue by Krish95** [iqbalansari/emacs-emojify#32]
Thank you for the wonderful package.

**Comment by iqbalansari** [comment]
Hi @Krish95,

Thanks for you kind words. I see you had some issue regarding emojify inhibit function, is that fixed?

**Comment by Krish95** [comment]
Yes, and thanks a lot for asking. 👍

**Comment by Krish95** [comment]
Hey, I just remembered that the inhibit function for "8)" only works if it's in the beginning of a line and thus when I have an indented list it breaks.
<img width="380" alt="screen shot 2017-11-04 at 9 05 35 pm" src="https://user-images.githubusercontent.com/7701992/32406728-f02180c4-c1a3-11e7-8ae2-902fcf387c7f.png">

**Comment by iqbalansari** [comment]
I see, it is impossible to detect whether "8)" is intended to be used as an emoji or just plain text. There are two ways you can avoid this

- Simply turn [off](https://github.com/iqbalansari/emacs-emojify#configuring-the-types-of-emojis-displayed) ascii emojis, i.e. add something like the following to your Emacs configuration. Please note this will disable display of all ascii emojis.

```lisp
(emojify-set-emoji-styles '(unicode github))
```

- Disable display of "8)" as emoji this can be done by adding a function to `emojify-inhibit-functions`, add something like following to you Emacs configuration.

```lisp
(defun my-disable-eight-paren-emoji (match &rest ignored)
  (string= match "8)"))

(add-hook 'emojify-inhibit-functions #'my-disable-eight-paren-emoji)
```

Hope that helps!

**Comment by Krish95** [comment]
Yup, that worked. Thanks a lot 👍
