### ISSUE TITLE
Slow performance when used with global-visual-line-mode or truncate-lines

### ISSUE THREAD

**Issue by yuhe00** [iqbalansari/emacs-emojify#34]
I'm experiencing slow performance when using this package with global-visual-line-mode or truncate-lines. The longer the line and the more lines it has to be split into, the slower it gets. There is no drop in performance if there are no emojis on the line. I've tested this on both Windows with [emax64-20171130](https://github.com/m-parashar/emax64) and on Manjaro Linux using Emacs 25.3. There is less slowdown on Linux, but I think that's just because it's much faster in general 😄

**Comment by iqbalansari** [comment]
Hi @yuhe00,

I have `global-visual-line-mode` on by default in my configuration and never experienced a slow down, would it be possible for you to post an example piece of text to reproduce the issue?

Thanks

**Comment by yuhe00** [comment]
This hasn't been a big issue for me since I switched over to Linux full-time for all Emacs-ing, but I did some testing again, both on Linux and Windows.

On Linux, it seems to only slow down when there are a lot of emojis on the same line, regardless of whether `global-visual-line-mode` is on or not, ie. something like this:

> :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face: :smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face::smile::slightly_smiling_face:

Slowdown is experienced when you try to edit that line, but not any other line. I think this is fine, nobody needs that many emojis on a single line anyway...

On Windows, there is slowdown even if there is a single emoji on a line, like this:

> The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog :smile: The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.

...which is not very usable. But this is likely an issue with Emacs on Windows (or emax64 in particular) and not emacs-emojify, so I'm going to close this issue for now. It's good to have this for reference in case anyone else encounter the same problem though.
