### ISSUE TITLE
Dosen't Work With Lists

### ISSUE THREAD

**Issue by tompurl** [iqbalansari/emacs-emojify#36]
Here's my Emacs version:

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-12 on hullmann, modified by Debian

Here's my font:

    (set-frame-font "Ubuntu Mono 14" nil t)

I'm using emojify in org mode. When I use it in a list the emoji aren't show as emoji. 

For example, this works:

    :P this is cool :)

But this does not

    - :P this is cool :)

Neither does this:

    1. :P this is cool :)

Thank you!

**Comment by iqbalansari** [comment]
Hi @tompurl,

Thanks for the bug report. I just tried the examples provided by you in org-mode and the emojis are displayed properly for all the three examples. Could you please confirm that you are using the latest version of `emojify`?

**Comment by tompurl** [comment]
Thank you for your quick response @iqbalansari. I checked again and it only seems to work this way when I'm using org-mode. Here's the minor modes I'm using:

    Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption 
    Blink-Cursor Electric-Indent Emojify File-Name-Shadow Flyspell Font-Lock 
    Global-Font-Lock Global-Undo-Tree Ido-Everywhere Line-Number 
    Menu-Bar Mouse-Wheel Org-Bullets Shell-Dirtrack Tooltip Transient-Mark
    Undo-Tree Yas Yas-Global

Do you have the same experience in org-mode?

**Comment by iqbalansari** [comment]
The minor modes list looks okay. I am not experiencing the issues you describe on my side. Could you please verify the version of `emojify` you are using, it should `20180128.607`.

**Comment by tompurl** [comment]
Ah yes, I forgot to include the version earlier. I'm was using 0.4, which I thought was the latest because it was the latest release. I then added the melpa repo (instead of just melpa-stable), installed the newer version and the problem has disappeared. Thank you for your help.

**Comment by iqbalansari** [comment]
I have added the release tag, MELPA Stable should be updated soon. Also I would suggest that you remove the MELPA repo since it override the updates from MELPA Stable. Thanks!

**Comment by tompurl** [comment]
Wonderful, thank you for the new version and tip. I didn't know how unstable plain-old MELPA could be. 

And thank you for creating such a great minor mode! I'm using it to annotate my book notes and find it to already be indispensable.

**Comment by iqbalansari** [comment]
Thanks for the kind words 😊
