### ISSUE TITLE
Feature Request: auto-complete-mode integration.

### ISSUE THREAD

**Issue by Idorobots** [iqbalansari/emacs-emojify#37]
It would be a nice integration for this battle-critical module and there already is `emojify-list-emojis`, so part of the needed functionality is probably already there.

Also, there seems to be [a module that does Unicode emoji autocompletion](https://github.com/syohex/emacs-ac-emoji) written already so maybe that could be re-used in emojify?

**Comment by iqbalansari** [comment]
Hi @Idorobots,

Emojify already integrates with `company-mode` (though it is off by default, see the [README](https://github.com/iqbalansari/emacs-emojify#displaying-emojis-in-company-mode-tooltips) for steps for enabling it), you can try [`company-emoji`](https://github.com/dunn/company-emoji).

While implementing support for `company-mode`, I had looked at `autocomplete-mode` too but it seemed impossible to display emojis in auto-complete modes tooltip (at least with their current implementation)

Thanks
