### ISSUE TITLE
Show emoji in subject in mu4e headers buffer.

### ISSUE THREAD

**Issue by bradyt** [iqbalansari/emacs-emojify#39]
I'd like to see emoji that some companies are sending in the subject line of emails.

My quick fix now is to uninhibit emojify there, with

``` elisp
(with-eval-after-load "emojify"
  (delete 'mu4e-headers-mode emojify-inhibit-major-modes))
```

Then I make sure there's no emoji in the `mu4e-headers-*-mark` family.

I see there's an `emojify-inhibit-functions` used for org-mode lists and tags, but haven't researched further yet.

**Comment by iqbalansari** [comment]
Hi @bradyt,

Thanks for the bug report and sorry for the late reply. 

If I understood you correctly, you want to display the emojis **only** in the subject lines of the emails. As you have already figured out `emojify-inhibit-functions` is the correct place to add such customizations. You will still need to remove `mu4e-headers-mode` from `emojify-inhibit-major-modes`

Thanks
