### ISSUE TITLE
Question: easily filter whether to insert github or utf-8 emojis?

### ISSUE THREAD

**Issue by haywirez** [iqbalansari/emacs-emojify#40]
Hi, I love this but often find myself resorting to a web cheatsheet still 😕 I'm using `ido-mode` for autocompletion. The list gets slow in the popup, do you have a suggestion for an an easy way to filter out a full list of github emoji only (for commits) and utf-8 (for text)?

**Comment by iqbalansari** [comment]
Hi @haywirez,

Thanks for the bug report and sorry for the late reply. There currently isn't a mechanism to do so, however you can perhaps build your own commands using `emojify-completing-read`, you can provide a predicate to this function which is used to decide which emojis should be part suggestions, for example the following would suggest only `github` emojis

```elisp
(emojify-completing-read "Select a Github style emoji: "
                         (lambda (emoji data)
                           (equal (gethash "style" data) "github")))
```

While the following would suggest only `unicode` style emojis

```elisp
(emojify-completing-read "Select a unicode style emoji: "
                         (lambda (emoji data)
                           (equal (gethash "style" data) "unicode")))
```

See the [docstring](https://github.com/iqbalansari/emacs-emojify/blob/38ae28d95b58e9fb86a3495a2dda3e5de254c4fc/emojify.el#L1752-L1771) of `emojify-completing-read` for more details. Hope that helps

Thanks

**Comment by iqbalansari** [comment]
Hello @haywirez, closing this since I believe `emojify-completing-read` can be used to achieve the customization you needed

**Comment by haywirez** [comment]
Thank you for the helpful explanation and the reminder! I haven't got around trying it, until now 🙏

**Comment by iqbalansari** [comment]
Sure, let me know if you have any additional questions
