### ISSUE TITLE
emojify-mode can prevent user from fast-typing any text into Emacs

### ISSUE THREAD

**Issue by AlonTzarafi** [iqbalansari/emacs-emojify#43]
With emojify-mode, typing 2 letters on the keyboard (for example "as") very fast, almost at once, where both keys are pushed down, results in Emacs inserting only the first letter ("a") and then beeping the bell and showing "Quit" in the echo area. (It's as if you pressed the letter "a" and then pressed C-g, where in every other situation it would have simply been accepted as "a" and "s" keystrokes)

It's a very cool package but I had to disable it because it wouldn't let me type (or rather, type fast).

Using Emacs 26.1 build 1 on Windows

**Comment by marcbowes** [comment]
OSX too.

The easiest way to see this is to have a really slow buffer and then do something like isearch. Making a slow buffer is easy - just have a really long line.

**Comment by cfuhrman** [comment]
I'm seeing the same behavior, which started when I updated from Emacs 25.3 to 26.1.

**Comment by gcv** [comment]
I think this behavior occurred in 25.3 also, but it's much more pronounced in 26.x At least on macOS (NextStep port), 26 has worse display performance than 25, so slowdowns like this are more noticeable. The problem exists as of the 26.2pretest2 release.

**Comment by iqbalansari** [comment]
Hi, could you please mention the setup you are using emojify with, I would need the OS version, Emacs version and `emojify` version.

I am using the Ubuntu v16.04, Emacs v26.1 and emojify v20181221.350 (latest from MELPA) and I do not see any issues while typing.

Additionally could you do `debug-on-quit` this would print the stacktrace of what was happening when the quit happened.

Also there was an [issue](https://github.com/iqbalansari/emacs-emojify/issues/41) that was reported earlier about emojify's performance on Emacs 26.1, so make sure you are using the latest version of emojify

Thanks

**Comment by gcv** [comment]
Thanks for looking into this!

- macOS 10.14.2
- GNU Emacs 26.1.91 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.2 (Build 18C54))\n of 2019-01-07 (26.2pretest2)
- emojify version 20181221.350

`enable-debug-on-quit` and triggering the bug just gives me this unhelpful trace:
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

Profiling and triggering the bug gives me the following:
```
- command-execute                                                1273  79%
 - call-interactively                                            1273  79%
  + byte-code                                                    1048  65%
  - funcall-interactively                                         225  14%
   + isearch-printing-char                                        176  10%
   + isearch-exit                                                  30   1%
   + isearch-forward                                               17   1%
   + helm-M-x                                                       1   0%
- ...                                                             236  14%
   Automatic GC                                                   236  14%
  emojify-detect-emoji-entry/exit                                  93   5%
- timer-event-handler                                               3   0%
 - apply                                                            3   0%
  - auto-revert-buffers                                             3   0%
   + apply                                                          3   0%
+ redisplay_internal (C function)                                   1   0%
```

That was the only way I even guessed emojify caused the problem, it was the only unexpected thing.

**Comment by iqbalansari** [comment]
Hi @AlonTzarafi, @gcv I would your help in confirming the issue. Would you be able to run the following code after loading `emojify` and see if there is any improvement?

```elisp
(defun emojify-detect-emoji-entry/exit ()
  (emojify-with-saved-buffer-state
    (when emojify--last-emoji-pos
      (emojify-on-emoji-exit (car emojify--last-emoji-pos) (cdr emojify--last-emoji-pos)))

    (when (get-text-property (point) 'emojified)
      (let* ((text-props (text-properties-at (point)))
             (buffer (plist-get text-props 'emojify-buffer))
             (match-beginning (plist-get text-props 'emojify-beginning))
             (match-end (plist-get text-props 'emojify-end)))
        (when (eq buffer (current-buffer))
          (emojify-on-emoji-enter match-beginning match-end)
          (setq emojify--last-emoji-pos (cons match-beginning match-end)))))))


(defun emojify-update-visible-emojis-background-after-command ()
  (emojify--update-emojis-background-in-region-starting-at (window-start)))


(defun emojify-update-visible-emojis-background-after-window-scroll (_window display-start)
  (emojify--update-emojis-background-in-region-starting-at display-start))
```

**Comment by iqbalansari** [comment]
@cfuhrman What is the OS you are using?

**Comment by AlonTzarafi** [comment]
@iqbalansari I can confirm running this code makes the issue disappear :)

**Comment by AlonTzarafi** [comment]
@iqbalansari The fix works for me. Thanks

**Comment by gcv** [comment]
@iqbalansari Seems to work. Thank you.

**Comment by iqbalansari** [comment]
Cool, thanks for verifying! Closing this issue.
