### ISSUE TITLE
Support messages and echo area.

### ISSUE THREAD

**Issue by matthew-piziak** [iqbalansari/emacs-emojify#51]
I would like to be able to display emojis in echo area messages. That is, I want to be able to call `(message "<emoji>")` and have it display correctly.

I've tested `global-emojify-mode` and `global-emojify-mode-line-mode`. Emojis don't display. I've also tried `emojify-message` but it looks like that does something else.

**Comment by iqbalansari** [comment]
Hi @matthew-piziak,

If you control the code calling `message` then this is trivial, basically you will have to do something like

```elisp
(message (emojify-string "<emoji>"))
``` 
instead of

```elisp
(message "<emoji>")
```

However making this work in general might need a bit more work, will look into this.

**Comment by matthew-piziak** [comment]
Strange, if I do `(message (emojify-string "<C-x 8 RET SNOWFLAKE>"))` then I just get the literal `#("❄" 0 1 (emojified t emojify-display (image :type png :file "/home/matt/.emacs.d/emojis/emojione-v2.2.6-22/2744.png" :ascent center :heuristic-mask t :background "#F0FFF0" :scale ...) display (image :type png :file "/home/matt/.emacs.d/emojis/emojione-v2.2.6-22/2744.png" :ascent center :heuristic-mask t :background "#F0FFF0" :scale ...) emojify-text "❄"))` in the message buffer. It's clear that the emoji picture is downloaded, but it doesn't display.

**Comment by iqbalansari** [comment]
Actually when you evaluate something in Emacs (using <kbd>`C-x`</kbd><kbd>`C-e`</kbd>) the return value is echo in the minibuffer. `message` returns the string that was `echo`ed in this case Emacs is echoing back the literal string.

```elisp
(run-at-time 1.0 nil (lambda () (message (emojify-string "This is a test ❄"))))
```

**Comment by matthew-piziak** [comment]
Oh that totally works. Thank you so much!
