### ISSUE TITLE
global-emojify-mode-line-mode and nyan-mode

### ISSUE THREAD

**Issue by sheikki** [iqbalansari/emacs-emojify#52]
I'm using global-emojify-mode-line-mode and nyan-mode. Whenever I scroll the buffer down enough, a winking face emoji appears out of nowhere

![Screenshot from 2019-04-16 15-59-13](https://user-images.githubusercontent.com/4730559/56211465-a43b7e00-6060-11e9-9120-2bd8de75fd0f.png)

It disappears if I scroll the buffer up

Any idea what is going on?

From my .emacs

```
(use-package emojify
  :ensure t
  :init
  (global-emojify-mode)
  :config
  (setq emojify-emoji-set "twemoji-v12")
  (progn
    (add-hook 'after-init-hook 'global-emojify-mode-line-mode)))
```
This is Emacs 26.2. The same issue was present also in 26.1

**Comment by iqbalansari** [comment]
Hi @sheikki, thanks for the bug report, this was bug in `emojify` I have pushed a fix on master. Could you please try it once MELPA builds the latest version

**Comment by sheikki** [comment]
Yeah, sorry for the late confirmation. All is fine now, thanks :)

**Comment by iqbalansari** [comment]
No problem, thanks for the confirmation!
