### ISSUE TITLE
How to Use Ido with `emojify-completing-read`?

### ISSUE THREAD

**Issue by WammKD** [iqbalansari/emacs-emojify#57]
The documentation of `emojify-completing-read` note being able to use Ido (or Helm, etc.) with the function yet the function has hard-coded using `completing-read`; how would one go about use any of the other completion methods with the `emojify-completing-read` function?

**Comment by iqbalansari** [comment]
Hello @WammKD, sorry for the late reply, `emojify-completing-read` does not explicitly select an completion framework, it would use whatever you have configured to work with the rest of the Emacs. In case of `Ido` I think there used to be a package (`ido-everywhere`?) which used to configure Emacs to use `Ido` for all completions, similarly `helm` has `helm-mode` which makes `helm` the default completion framework

If I understand you are looking for a way to configure `emojify` such that it explicitly uses a particular framework right? Unfortunately `emojify` does not have any such feature, but this should be easy to add

**Comment by WammKD** [comment]
Hey, @iqbalansari; no worries! I take quite a bit to respond often enough, myself.

Yup; that's exactly what I'm looking for. While I rather like `Ido`, I absolutely hate when it crops into, say, opening a file or other such.

So I haven't used `ido-everywhere` since, well, I don't want it everywhere.

Would it help for me to look into adding the feature? I don't know how much free time I have, at the moment, but, of course, I'd love to help in any way that's useful.

**Comment by iqbalansari** [comment]
That would be great @WammKD, I will happily accept a PR implementing this, thanks!

**Comment by WammKD** [comment]
Took me forever, @iqbalansari, but got that PR in #70.

**Comment by iqbalansari** [comment]
I have merged your PR, MELPA should be updated in a bit, could you try out the update and confirm once MELPA is updated?

**Comment by 4tuw2tuv0** [comment]
Ooof; sorry I never responded to this. It's been a while but I remember it working really well. Thanks for being so helpful! And for an awesome package.

'Gonna close this so not to clog up your Issues.
