### ISSUE TITLE
Resolution too low

### ISSUE THREAD

**Issue by feklee** [iqbalansari/emacs-emojify#58]
On my hires display, and especially if I increase font size, the emojis are blurry. *Is it possible to increase the resolution of the emojis?*

EmojiOne or Twemoji both are blurry.

**Comment by feklee** [comment]
Found it out myself: The emoji sets with the `-22` postfix are *resized to 22px.* This is explained in:

    ~/.emacs.d/elpa/emojify-20190809.959/data/emoji-sets.json

After switching from `twemoji-v2-22` to `twemoji-v2`, the emojis look crisper.

**Comment by daroczig** [comment]
Thanks!

For future reference: `M-x` + `customize-variable`  + `emojify-emoji-set`

**Comment by tmalsburg** [comment]
I had the same problem.  Would be good to mention this in the README.org of this repository (which many people will consult for help).

Thanks for a great package!
