### ISSUE TITLE
Weird image files

### ISSUE THREAD

**Issue by jcs090218** [iqbalansari/emacs-emojify#62]
Some image are crop out like shown below.

| Wrong | Correct |
|:---|:---|
|![old](https://user-images.githubusercontent.com/8685505/76080122-32a25080-5fe1-11ea-9768-407b4993e879.png)|![new](https://user-images.githubusercontent.com/8685505/76080315-96c51480-5fe1-11ea-973d-a85fffbe005c.png)|

I couldn't identify the issue because I have two PC and only one has this issue. Both PC run on Windows 10 and with Emacs version `27.0.60`. I decided to report this just to acknowledge the author about this.

### Solution

The solution I found is that are **SOME** images from `tar` files listed in [data/emoji-sets.json](https://github.com/iqbalansari/emacs-emojify/blob/master/data/emoji-sets.json) has different compression method. Once I throw the image to Photoshop and re-exported then everything works (after reload the source images)!

These are the re-exported image files. But I don't what would it do to the current user?

https://drive.google.com/drive/folders/135_PsmIQ7DXtQkj5m8XyP1WoNPJA_kTv?usp=sharing

This is the `java` file I use to re-export all images file.

```java
import org.apache.commons.io.FilenameUtils;

import java.io.File;
import java.io.IOException;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public class ReExport_Image {
    private static String[] paths = {
        "./res/emojione-v2",
        "./res/emojione-v2.2.6/",
        "./res/emojione-v2.2.6-22/",
        "./res/emojione-v2-22/",
        "./res/twemoji-v2/",
        "./res/twemoji-v2-22/"
    };

    /**
     * Program entry.
     * @param args Program arguments.
     */
    public static final void main(String args[]) {
        for (String path : paths) {
            System.out.println("[DIRECTORY] Processing path: " + path);
            reExportImageDirectory(path);
        }
        System.out.println("[INFO] Done re-export process");
    }

    /**
     * Re-export all images under PATH (directory).
     * @param path Path that points to a directory.
     */
    private static void reExportImageDirectory(String path) {
        File dir = new File(path);
        File[] directoryListing = dir.listFiles();
        if (directoryListing != null) {
            for (File child : directoryListing) {
                String ext = FilenameUtils.getExtension(child.getPath());
                if ("png".equals(ext)) {
                    System.out.println("Processing image file: " + child.getPath());
                    reExportImageFile(child.getPath());
                }
            }
        }
    }

    /**
     * Re-export the image file by PATH.
     * @param path Image file path.
     */
    private static void reExportImageFile(String path) {
        try {
            File input = new File(path);
            File output = new File(path);
            BufferedImage im1 = ImageIO.read(input);
            BufferedImage im2 = new BufferedImage(im1.getWidth(), im1.getHeight(),
                                                  BufferedImage.TYPE_4BYTE_ABGR);
            im2.getGraphics().drawImage(im1, 0, 0, null);
            ImageIO.write(im2 , "png", output);
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }
}
```

Please test this patch, and let me know what are your thoughts! Thanks!

**Comment by iqbalansari** [comment]
This is awesome, thanks a lot @jcs090218 for taking time to investigate this issue. I will updating the images soon. The image update would not affect existing users, so that should not be a problem

**Comment by iqbalansari** [comment]
Fixed on master, please confirm once MELPA updates

**Comment by jcs090218** [comment]
Thanks! I appreciate your work and effort! :D

**Comment by jcs090218** [comment]
Looks good! Updated. Close this issue now.
