### ISSUE TITLE
Conflicts with org entites

### ISSUE THREAD

**Issue by ransomts** [iqbalansari/emacs-emojify#65]
Hi, great package but it is overriding [org modes pretty entities](https://orgmode.org/manual/Special-Symbols.html). Is there a way to toggle that conflict? I'd like to keep the emojis but prefer the latex symbol names from org.

**Comment by iqbalansari** [comment]
Hello @ransomts, thanks for the bug report, could you also provide an example which is not working for you

I have the following in an `org-mode` buffer and it seems to be working fine

```
This is \pi :)
```

And it seems to be rendered fine

![Screenshot from 2020-04-22 20-55-11](https://user-images.githubusercontent.com/2726057/80001126-a50cb880-84db-11ea-9c80-8b814ddc2d8f.png)

**Comment by ransomts** [comment]
The case that brought it to my attention is  `\leftrightarrow` which upon looking through the `org-entities-help` command might be the only one. Here's a screenshot of two org buffers with and without the emjois turned on:

![emoji-bug](https://user-images.githubusercontent.com/8659901/80013367-c00c0800-849c-11ea-9105-7ffd6a3d6446.png)

Thanks for the response!

**Comment by iqbalansari** [comment]
I see can you try setting `emojify-composed-text-p` to `nil`, that should fix this

**Comment by ransomts** [comment]
that does display the correct arrow, but I lose my :) faces with that. :(

**Comment by iqbalansari** [comment]
Can you share the text for which it is failing, the following and it seems to be displayed as expected

```
\leftrightarrow :)
```

**Comment by iqbalansari** [comment]
Hello @ransomts any update on this?

**Comment by ransomts** [comment]
Sorry got distracted from this - not sure what I saw the other day but it's passing all my tests this morning. Thanks for following up!

**Comment by iqbalansari** [comment]
No problem, thanks for confirming
