### ISSUE TITLE
Error on completion with company-capf

### ISSUE THREAD

**Issue by atimchenko92** [iqbalansari/emacs-emojify#74]
This is the original issue: https://github.com/company-mode/company-mode/issues/1000#

It looks like Emojify messes with `ad-Advice-company-pseudo-tooltip-unhide`

Configuration snippets:
``` elisp
(use-package emojify
  :ensure t
  :custom
  ;; Set emojify to only replace Unicode emoji, and do it everywhere.
  (emojify-emoji-styles '(unicode))
  (emojify-inhibit-major-modes '())
  :hook
  ((after-init . global-emojify-mode-line-mode)
   (after-init . global-emojify-mode)))

  (use-package company-emoji
     :ensure t
     :config
     (company-emoji-init))

```

Possible related issues: #54

**Comment by iqbalansari** [comment]
Hello @atimchenko92, thanks for the bug report, I have pushed a fix on master, can you try the latest version on Melpa and verify if the issue is stil happening.

Thanks

**Comment by atimchenko92** [comment]
Hi @iqbalansari,
it looks good! Thanks for your work :)

**Comment by dgutov** [comment]
Actually, I got a report regarding this one, not the one left a comment in 2 hours ago (and now deleted).

And the reason was that the fix is not in melpa-stable. :-(
