### ISSUE TITLE
Can I manually download emoji fonts and still make everything works?

### ISSUE THREAD

**Issue by ccmywish** [iqbalansari/emacs-emojify#76]
I can't connect to raw.githubusercontent.com when trying "emojify-download-emoji" . This is because of the regional limit in China. So after I manually download the emoji fonts, how can I make emojify works ?  Could anyone help me ?

**Comment by xuehy** [comment]
How do you solve it?

**Comment by ccmywish** [comment]
> How do you solve it?

Just download all the emoji fonts from `emoji-sets.json` in this repo, and install them manually.
