### ISSUE TITLE
Example for predicate in emojify-completing-read doesn't work 

### ISSUE THREAD

**Issue by thiderman** [iqbalansari/emacs-emojify#79]
The documentation for `emojify-completing-read` has an example for how to use the `predicate` argument;

```
(emojify-completing-read "Select a Github style emoji: "
                         (lambda (emoji data)
                           (equal (gethash "style" data) "github")))
```

This doesn't work, since the lambda only gets one argument;
```
lispy--eval-elisp: Wrong number of arguments: (lambda (emoji data) (equal (gethash "style" data) "github")), 1
```

It doesn't seem like the `data` is passed anymore? Did that change and the docstring was accidentally left behind?

**Comment by iqbalansari** [comment]
Oh yes, you are correct @thiderman. The arguments to the predicate changed from `emoji`, `data` to just a string for the form `<emoji> - <name> (<style>)`. I will update the docstrings. Thanks for reporting this

**Comment by iqbalansari** [comment]
I have updated the docstrings, closing this thanks again!
