### ISSUE TITLE
apropos-emoji

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#8]
It would be nice to offer an apropos-emoji command to help people find their favorites.

**Comment by iqbalansari** [comment]
Sounds useful. Have you tried [company-emoji](https://github.com/dunn/company-emoji)? It kind of does what you want.

**Comment by ryanprior** [comment]
`company-emoji` and `ac-emoji` are useful and I like them, but they still require you to know at least the first couple letters of the emoji name you want. For example, if I want a rain cloud, I have to know to start typing `:cloud-with-rain:`. If I start typing `:rai` it'll offer me `:rainbow:` and `:railway-track:` but nothing rain cloud-related.

Of course, we could create duplicate symbols for emojis so that a rain cloud can be found under either `cloud-with-rain` or `rain-cloud`. But there would be tons of them. Apropos search is really a better way to help people find the right name.

I might worry that apropos search doesn't really fit in this package. After all, we don't need a single package to serve every possible emoji-related need. But I also think some things in this package will tend to be duplicated in others.

One possibility to resolve this going forward would be to extract reasonably general-purpose emoji data and code into an `emoji-common` core which this package and others like `company-emoji` and a hypothetical `apropos-emoji` can rely upon.

**Comment by iqbalansari** [comment]
> I might worry that apropos search doesn't really fit in this package ... One possibility to resolve this going forward would be to extract reasonably general-purpose emoji data and code into an emoji-common core

I agree with you. But for the time being I think we can add it to this package itself, until we feel the package is in a stable state.

**Comment by iqbalansari** [comment]
Hi,

I have [added](https://github.com/iqbalansari/emacs-emojify/tree/master#usage) two new commands to `emojify-apropos-emoji` and `emojify-insert-emoji`. Hopefully they do what you had requested. Could you please try them once MELPA updates?

Thanks

**Comment by ryanprior** [comment]
I ran `(emojify-apropos-emoji "cat")` and got this:

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  maphash(#[514 "\302	\"\204\302	\303\304\"\"\205#\300\305!\305\303\304\"!]E\300\242B\240\207" [(nil) apropos-regexp string-match gethash "name" apropos-score-str] 8 "\n\n(fn KEY VALUE)"] nil)
  emojify-apropos-emoji("cat")
  eval((emojify-apropos-emoji "cat") nil)
  eval-expression((emojify-apropos-emoji "cat") nil)
  funcall-interactively(eval-expression (emojify-apropos-emoji "cat") nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```
I get the same result when I run the command interactively.

**Comment by ryanprior** [comment]
Update: after removing the package and re-installing, then re-downloading the emoji files, the above command works as expected. I tried to reproduce the error but have been so far unsuccessful.

**Comment by iqbalansari** [comment]
Hmm let me see if I can reproduce this, is there any suggestion you have with respect to the functionality?

**Comment by iqbalansari** [comment]
Closed by mistake sorry

**Comment by ryanprior** [comment]
The functionality looks good, this is useful. I did manage to reproduce the bug by restarting emacs and using `emojify-apropos-emoji` before I had enabled `emojify-mode` in any buffers.

**Comment by iqbalansari** [comment]
> I did manage to reproduce the bug by restarting emacs and using emojify-apropos-emoji before I had enabled emojify-mode in any buffers.

I see, I had fixed this but not merged it with master, I have updated master, next MELPA build will have the fixed version. I am closing this issue. Thanks for testing :+1:
